In [5]:
# p.158
import seaborn as sns
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [7]:
# nice aggregation feature
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [10]:
planets.groupby('method').head()

,method,number,orbital_period,mass,distance,year
0,Radial Velocity,1,269.300000,7.10,77.40,2006
1,Radial Velocity,1,874.774000,2.21,56.95,2008
2,Radial Velocity,1,763.000000,2.60,19.84,2011
3,Radial Velocity,1,326.030000,19.40,110.62,2007
4,Radial Velocity,1,516.220000,10.50,119.47,2009
29,Imaging,1,NaN,NaN,45.52,2005
30,Imaging,1,NaN,NaN,165.00,2007
31,Imaging,1,NaN,NaN,140.00,2004
32,Eclipse Timing Variations,1,10220.000000,6.05,NaN,2009
33,Imaging,1,NaN,NaN,NaN,2008
34,Imaging,1,NaN,NaN,145.00,2013
37,Eclipse Timing Variations,2,5767.000000,NaN,130.72,2008
38,Eclipse Timing Variations,2,3321.000000,NaN,130.72,2008
39,Eclipse Timing Variations,2,5573.550000,NaN,500.00,2010
40,Eclipse Timing Variations,2,2883.500000,NaN,500.00,2010
91,Transit,1,1.508956,NaN,NaN,2008
92,Transit,1,1.742994,NaN,200.00,2008
93,Transit,1,4.256800,NaN,680.00,2008
94,Transit,1,9.202050,NaN,NaN,2008
95,Transit,1,4.037896,NaN,NaN,2009
113,Astrometry,1,246.360000,NaN,20.77,2013
537,Astrometry,1,1016.000000,NaN,14.98,2010
680,Transit Timing Variations,2,160.000000,NaN,2119.00,2011
736,Transit Timing Variations,2,57.011000,NaN,855.00,2012
749,Transit Timing Variations,3,NaN,NaN,NaN,2014
787,Orbital Brightness Modulation,2,0.240104,NaN,1180.00,2011
788,Orbital Brightness Modulation,2,0.342887,NaN,1180.00,2011
792,Orbital Brightness Modulation,1,1.544929,NaN,NaN,2013
813,Transit Timing Variations,2,22.339500,NaN,339.00,2013
902,Microlensing,1,NaN,NaN,NaN,2008
903,Microlensing,1,NaN,NaN,NaN,2008
904,Microlensing,1,NaN,NaN,NaN,2009
905,Microlensing,1,NaN,NaN,3600.00,2013
906,Microlensing,1,2780.000000,NaN,NaN,2011
941,Pulsar Timing,3,25.262000,NaN,NaN,1992
942,Pulsar Timing,3,66.541900,NaN,NaN,1992
943,Pulsar Timing,3,98.211400,NaN,NaN,1994
944,Pulsar Timing,1,36525.000000,NaN,NaN,2003
945,Pulsar Timing,1,0.090706,NaN,1200.00,2011
958,Pulsation Timing Variations,1,1170.000000,NaN,NaN,2007

In [13]:
planets.groupby('method')['orbital_period'].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64